require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DotsmembersController do

  # This should return the minimal set of attributes required to create a valid
  # Dotsmember. As you add validations to Dotsmember, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DotsmembersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dotsmembers as @dotsmembers" do
      dotsmember = Dotsmember.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dotsmembers).should eq([dotsmember])
    end
  end

  describe "GET show" do
    it "assigns the requested dotsmember as @dotsmember" do
      dotsmember = Dotsmember.create! valid_attributes
      get :show, {:id => dotsmember.to_param}, valid_session
      assigns(:dotsmember).should eq(dotsmember)
    end
  end

  describe "GET new" do
    it "assigns a new dotsmember as @dotsmember" do
      get :new, {}, valid_session
      assigns(:dotsmember).should be_a_new(Dotsmember)
    end
  end

  describe "GET edit" do
    it "assigns the requested dotsmember as @dotsmember" do
      dotsmember = Dotsmember.create! valid_attributes
      get :edit, {:id => dotsmember.to_param}, valid_session
      assigns(:dotsmember).should eq(dotsmember)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dotsmember" do
        expect {
          post :create, {:dotsmember => valid_attributes}, valid_session
        }.to change(Dotsmember, :count).by(1)
      end

      it "assigns a newly created dotsmember as @dotsmember" do
        post :create, {:dotsmember => valid_attributes}, valid_session
        assigns(:dotsmember).should be_a(Dotsmember)
        assigns(:dotsmember).should be_persisted
      end

      it "redirects to the created dotsmember" do
        post :create, {:dotsmember => valid_attributes}, valid_session
        response.should redirect_to(Dotsmember.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dotsmember as @dotsmember" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dotsmember.any_instance.stub(:save).and_return(false)
        post :create, {:dotsmember => {}}, valid_session
        assigns(:dotsmember).should be_a_new(Dotsmember)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dotsmember.any_instance.stub(:save).and_return(false)
        post :create, {:dotsmember => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dotsmember" do
        dotsmember = Dotsmember.create! valid_attributes
        # Assuming there are no other dotsmembers in the database, this
        # specifies that the Dotsmember created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dotsmember.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dotsmember.to_param, :dotsmember => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dotsmember as @dotsmember" do
        dotsmember = Dotsmember.create! valid_attributes
        put :update, {:id => dotsmember.to_param, :dotsmember => valid_attributes}, valid_session
        assigns(:dotsmember).should eq(dotsmember)
      end

      it "redirects to the dotsmember" do
        dotsmember = Dotsmember.create! valid_attributes
        put :update, {:id => dotsmember.to_param, :dotsmember => valid_attributes}, valid_session
        response.should redirect_to(dotsmember)
      end
    end

    describe "with invalid params" do
      it "assigns the dotsmember as @dotsmember" do
        dotsmember = Dotsmember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dotsmember.any_instance.stub(:save).and_return(false)
        put :update, {:id => dotsmember.to_param, :dotsmember => {}}, valid_session
        assigns(:dotsmember).should eq(dotsmember)
      end

      it "re-renders the 'edit' template" do
        dotsmember = Dotsmember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dotsmember.any_instance.stub(:save).and_return(false)
        put :update, {:id => dotsmember.to_param, :dotsmember => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dotsmember" do
      dotsmember = Dotsmember.create! valid_attributes
      expect {
        delete :destroy, {:id => dotsmember.to_param}, valid_session
      }.to change(Dotsmember, :count).by(-1)
    end

    it "redirects to the dotsmembers list" do
      dotsmember = Dotsmember.create! valid_attributes
      delete :destroy, {:id => dotsmember.to_param}, valid_session
      response.should redirect_to(dotsmembers_url)
    end
  end

end
